# Generated by Django 2.2.5 on 2020-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
