# Generated by Django 2.2.5 on 2020-08-15 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200815_0720'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bookinfo',
            table='book',
        ),
        migrations.AlterModelTable(
            name='peopleinfo',
            table='people',
        ),
    ]
