# Generated by Django 2.2.5 on 2020-08-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200816_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peopleinfo',
            name='name',
            field=models.CharField(db_index=True, max_length=10, verbose_name='人物'),
        ),
    ]
